version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgresun
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: ecommerceDB
    volumes:
      - ./database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432